### ISSUE TITLE
Relationship between `Person` and `DeploymentNode`

### ISSUE THREAD

**Issue by toorog** [structurizr/structurizr#18]
According to the C4 Model, a Person is `...one of the human users of your software system (e.g. actors, roles, personas, etc).`, whereas a DeploymentNode represents something hosting a software system instance (e.g. a server).

Assuming the following Model:

```
server_admin = person "Administrator" "Administrator of servers"
application = softwareSystem "Application 1" "My Application"
...
server = deploymentNode "Server" "My Server" "Server Operating System" {
    softwareSystemInstance application
}
server_admin -> server "Maintains"
```

In this scenario parsing the DSL fails with the message `A relationship between "Person://Administrator" and "DeploymentNode://server" is not permitted`.

This is due to the checks performed here, which do not allow relationships btw. DeploymentNodes and persons: https://github.com/structurizr/dsl/blob/b24b0999a5a985fe985d96f03a351c2fbb1fab08/src/main/java/com/structurizr/dsl/AbstractRelationshipParser.java#L19

Assuming that there is in general nothing wrong with the way I modeled the above example, I consider this to be a possible missing if condition in the checks linked above.

**Comment by simonbrowndotje** [comment]
Relationships between people and deployment nodes aren't supported I'm afraid ... by the DSL, the underlying Java client library, and the Structurizr renderer. I've transferred the issue, and tagged it as a feature request.

**Comment by MLNW** [comment]
This came to me as a surprise as well. I would have expected that users can be added to a deployment diagram.

**Comment by GiuseppeMP** [comment]
Same issue here, any update?

**Comment by Morozzzko** [comment]
Chiming in!

Here's my use-case for this feature:

Have a diagram which shows a high-level overview of our infrastructure and it includes nodes used by internal users (inc. VPN) and external ones. We already have a diagram showcasing data flow, and it's pretty good for our use-case.

I wanted to replicate it using model, but got the error and google led me there

Surely, the text of my message hints that I might have created perspectives instead of just adding different users to the diagram. That's the solution I'd take, but it'd make different entrypoints a bit more difficult to locate
