### ISSUE TITLE
View-specific styles

### ISSUE THREAD

**Issue by AndyMcKenna** [structurizr/structurizr#29]
I've got a model with 3 systems that I own and a number of systems that I don't.  I've got a systemContext view for each system that I own but I'd like to be able to associate styles to specific views.  When I'm in systemContext view "InventorySystem", I'd like system tag INVT to be dark blue and the other 2 are the default but when I'm in systemContext view "PricingSystem" then tag "PRCE" should be blue and "INVT" the default.

Right now I'm associating styles with Tags but it would be nice to be able to give a Style an optional View that it only applies to.

```
systemContext inventorySystem "InventorySystem" "Inventory system diagram" {
    include *
}
        
systemContext pricingSystem "PricingSystem" "Pricing system diagram" {
    include *
}
    
styles {
    element "INVT" {
        background #1168bd
    }
    element "PRCE" {
        background #1168bd
    }
}

**Comment by simonbrowndotje** [comment]
Structurizr is designed so that all elements have the same style on all diagrams within a workspace ... so you'll need to use the `!include` mechanism and split the single workspace up into 3 separate workspaces to get different styling. The "Big Bank" example has a demonstration of this -> https://github.com/structurizr/cli/tree/master/examples/big-bank-plc

**Comment by AndyMcKenna** [comment]
That makes sense, thank you.
