### ISSUE TITLE
Unable to click and drag on Lite

### ISSUE THREAD

**Issue by fabiocarneiro** [structurizr/structurizr#90]
With the diagram zoomed in, I am unable to click, hold and drag on Structurizr/Lite

It can be reproduced both in Chrome Version 102.0.5005.61 (Official Build) (64-bit) and Firefox 100.0.2 (64-bit)

**Comment by fabiocarneiro** [comment]
No. that one works fine. 

Ubuntu 21.10

**Comment by simonbrowndotje** [comment]
Thanks. It's because the diagrams in Lite are editable, and canvas dragging is only enabled for read-only diagrams. I've made a change so that diagrams with automatic layout are draggable (because they are, in effect, read-only too), but editable diagrams with manual layout still won't be draggable.
