### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by cappelaere** [structurizr/structurizr#96]
![image](https://user-images.githubusercontent.com/7567/177321006-a5b93428-0eca-492a-bc36-af114a4e5db0.png)

**Comment by cappelaere** [comment]
This is from a pull I did this morning using:
docker pull structurizr/lite
I loaded it into AWS ECR to scan for vulnerabilities.  This is the result: 4 Critical, 2 High, 3 Medium, 1 Low.  These are a little concerning to run into an operational environment.  They seem to be fairly easy to resolve by updating some libraries like openssl... I was not sure if you knew about this.

**Comment by simonbrowndotje** [comment]
These vulnerabilities are mostly in the base Docker image, and I've yet to find an image that doesn't have the same/similar issues. Since most people are only using this locally on their own developer machines, the risk of these vulnerabilities being exploited is very low. That said, there's a Spring Boot version of Structurizr Lite if you'd like to use that directly, or to build your own image. See https://structurizr.com/help/lite/getting-started for details.

**Comment by simonbrowndotje** [comment]
The Java EE web application is now available to download too, enabling you to build your own Docker image. See https://structurizr.com/help/lite/getting-started#javaee for more.
