### ISSUE TITLE
Commenting different parts of a documentation page

### ISSUE THREAD

**Issue by TheLazzziest** [structurizr/structurizr#99]
Hello! Does Structurizr support commenting different parts of a document similar to one which Confluence or Google docs does?  I haven't found any mentioning of that feature.

**Comment by simonbrowndotje** [comment]
It doesn't I'm afraid, and likely isn't a feature that will added given the way that the toolchain works.

**Comment by TheLazzziest** [comment]
Any reasoning behind that decision ? If you don't mind.

**Comment by simonbrowndotje** [comment]
The Structurizr cloud service/on-premises installation/Lite is used to publish "diagrams/docs as code", and the toolchain is a (mostly) one way publishing pipeline. If you add comments via the Structurizr UI, you'd need a way to (1) store them and (2) merge them back into the original docs as code files (or at least retain the comments the next time the workspace is published). So adding comments via the UI doesn't really fit the workflow I'm afraid.

**Comment by TheLazzziest** [comment]
>  If you add comments via the Structurizr UI, you'd need a way to (1) store them

I am not sure about concerns regarding storing them. Why not just to store them the same way as it has been done for comments for diagram reviewing feature? I suppose it must be some db storage. At least, I see that Structurizr reprensents these code files with documentation as a virtually single document, so I suppose it is possible to keep messages in memory/cache using keys of the following structure, for example: `<user>:<startpos>:<endpos>`. 

> (2) merge them back into the original docs as code files

Why do we need to merge them back ? Based on my suggestion above, we can just put comments according to their positions during rendering step (maybe I am missing smth here) 

Based on looking at review feature I've come up with a similar idea for documentation. I think this should increase a team's velocity since it won't be necessary to go back and forth between Structurizr and git in order to figure what a conversation is about. Moreover, sometimes people need to start a conversation without any changes, so git won't work in this case (if managers for example want to leave some comments here and there)

> at least retain the comments the next time the workspace is published

I thought documentation would be orthogonal to workspace versioning (maybe because of I have been using Lite version until now) in the context of differences between them. It won't matter what a document version is as long as the structure of the document remains the same, will it ? 

Thank you in advance.

**Comment by simonbrowndotje** [comment]
> I thought documentation would be orthogonal to workspace versioning (maybe because of I have been using Lite version until now) in the context of differences between them.

No, the documentation is inlined into the workspace (for both Lite and the CLI) ... you can see this if you export your workspace as a JSON file, and open it in a text editor. 

> It won't matter what a document version is as long as the structure of the document remains the same, will it ?

It will though, because any changes to the source documentation (the Markdown/AsciiDoc) potentially changes the structure, making something like a `<user>:<startpos>:<endpos>` scheme invalid. Confluence/Google Docs don't have this issue because you're editing the documentation in the same place that you're adding comments. That's not the case for what Structurizr does, which is rendering externally authored Markdown/AsciiDoc in the web browser as HTML.

The only way to make this work is to take the same approach as the diagram review feature ... i.e. take a copy of the documentation out of the workspace, and use that as the basis for comments. And I don't really want to do that I'm afraid.
